#!/bin/bash


#--------------- system_audit.sh----------------------#

report_dir="$HOME/system_report"
Time=$(TZ="America/New_York" date +"%Y-%m-%d_%H-%M-%S")
report_file="$report_dir/system_audit_report_$Time.txt"
Current_User=$(whoami)

# checking to see if directory exist

if [ ! -d "$report_dir" ]; then 
	mkdir -p "$report_dir"
fi

# Report Creation 
{
	echo "------------- System Audit Report ---------------------"
	echo "Created by: $Current_User"		# displaying who the report was generated by
	echo "Time Created: $Time"			# displaying time when report was generated 
	echo " "
	echo " " 
	
	echo "------------- Checking Logged-in Users-----------------"
	echo "currently logged-in: "
	who						# who command prints who is currently actively logged in to the system	
	echo " "
	echo " "

	echo "------------- Checking Last Log in Attempt ------------"
	echo "Now Displaying the Last 20 Log-in attempts... "
	echo " "
	last -n 20					# last command print last log in attmepts with a current limit of 20 to not flood screen with info
	echo " "
	echo " "

	echo "------------- Checking Network Connections ------------"
	# since ss is modern version of netstat, check if ss is utilized first 
	echo " "
	if command -v ss >/dev/null 2>&1; then 
		ss -tuln
	elif command -v netstat >/dev/null 2>&1; then
		netstat -tuln
	fi
	echo " "
	echo " "
	echo "------------- End of Report ---------------------------"

} >> "$report_file" 					# sending report to report file in the system report directory

echo "report_file sent!"	#confirmation
